### PR TITLE
refactor: add requirments.txt so anyone can easily install all depend…

### PR DESCRIPTION
**Pull request by pzpsofficial**
Add requirments.txtso anyone can easily install project dependencies. Skipped adding a python virtual env, let me know if we want to add this.

### CODE REVIEW

**Comment by pzpsofficial** [comment]
@KarolinaKaczmarczyk1 I was wondering about implementing python venv, what do you think?

**Comment by KarolinaKaczmarczyk1** [comment]
This is a very good idea. Take care of it

**Comment by KarolinaKaczmarczyk1** [comment]
I think at this stage of the project it is not necessary. We'll deal with it later.

**Review by KarolinaKaczmarczyk1 — COMMENTED** [review]
Please add comments in the code

**Review by KarolinaKaczmarczyk1 — APPROVED** [review]
Everything is great. You can merge

**Pull request merged**
